// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: bkfind/bkfind.proto

package bkfind

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Author string `protobuf:"bytes,1,opt,name=author,proto3" json:"author,omitempty"`
}

func (x *BReq) Reset() {
	*x = BReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bkfind_bkfind_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BReq) ProtoMessage() {}

func (x *BReq) ProtoReflect() protoreflect.Message {
	mi := &file_bkfind_bkfind_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BReq.ProtoReflect.Descriptor instead.
func (*BReq) Descriptor() ([]byte, []int) {
	return file_bkfind_bkfind_proto_rawDescGZIP(), []int{0}
}

func (x *BReq) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

type BReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Books string `protobuf:"bytes,1,opt,name=books,proto3" json:"books,omitempty"`
}

func (x *BReply) Reset() {
	*x = BReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bkfind_bkfind_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BReply) ProtoMessage() {}

func (x *BReply) ProtoReflect() protoreflect.Message {
	mi := &file_bkfind_bkfind_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BReply.ProtoReflect.Descriptor instead.
func (*BReply) Descriptor() ([]byte, []int) {
	return file_bkfind_bkfind_proto_rawDescGZIP(), []int{1}
}

func (x *BReply) GetBooks() string {
	if x != nil {
		return x.Books
	}
	return ""
}

type AReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Book string `protobuf:"bytes,1,opt,name=book,proto3" json:"book,omitempty"`
}

func (x *AReq) Reset() {
	*x = AReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bkfind_bkfind_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AReq) ProtoMessage() {}

func (x *AReq) ProtoReflect() protoreflect.Message {
	mi := &file_bkfind_bkfind_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AReq.ProtoReflect.Descriptor instead.
func (*AReq) Descriptor() ([]byte, []int) {
	return file_bkfind_bkfind_proto_rawDescGZIP(), []int{2}
}

func (x *AReq) GetBook() string {
	if x != nil {
		return x.Book
	}
	return ""
}

type AReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Authors string `protobuf:"bytes,1,opt,name=authors,proto3" json:"authors,omitempty"`
}

func (x *AReply) Reset() {
	*x = AReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bkfind_bkfind_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AReply) ProtoMessage() {}

func (x *AReply) ProtoReflect() protoreflect.Message {
	mi := &file_bkfind_bkfind_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AReply.ProtoReflect.Descriptor instead.
func (*AReply) Descriptor() ([]byte, []int) {
	return file_bkfind_bkfind_proto_rawDescGZIP(), []int{3}
}

func (x *AReply) GetAuthors() string {
	if x != nil {
		return x.Authors
	}
	return ""
}

var File_bkfind_bkfind_proto protoreflect.FileDescriptor

var file_bkfind_bkfind_proto_rawDesc = []byte{
	0x0a, 0x13, 0x62, 0x6b, 0x66, 0x69, 0x6e, 0x64, 0x2f, 0x62, 0x6b, 0x66, 0x69, 0x6e, 0x64, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x62, 0x6b, 0x66, 0x69, 0x6e, 0x64, 0x22, 0x1e, 0x0a,
	0x04, 0x42, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x22, 0x1e, 0x0a,
	0x06, 0x42, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x6f, 0x6f, 0x6b, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x62, 0x6f, 0x6f, 0x6b, 0x73, 0x22, 0x1a, 0x0a,
	0x04, 0x41, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x6f, 0x6b, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x62, 0x6f, 0x6f, 0x6b, 0x22, 0x22, 0x0a, 0x06, 0x41, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x73, 0x32, 0x64, 0x0a,
	0x06, 0x46, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x2b, 0x0a, 0x09, 0x46, 0x69, 0x6e, 0x64, 0x42,
	0x6f, 0x6f, 0x6b, 0x73, 0x12, 0x0c, 0x2e, 0x62, 0x6b, 0x66, 0x69, 0x6e, 0x64, 0x2e, 0x42, 0x52,
	0x65, 0x71, 0x1a, 0x0e, 0x2e, 0x62, 0x6b, 0x66, 0x69, 0x6e, 0x64, 0x2e, 0x42, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x22, 0x00, 0x12, 0x2d, 0x0a, 0x0b, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x75, 0x74, 0x68,
	0x6f, 0x72, 0x73, 0x12, 0x0c, 0x2e, 0x62, 0x6b, 0x66, 0x69, 0x6e, 0x64, 0x2e, 0x41, 0x52, 0x65,
	0x71, 0x1a, 0x0e, 0x2e, 0x62, 0x6b, 0x66, 0x69, 0x6e, 0x64, 0x2e, 0x41, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x22, 0x00, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x62, 0x6b, 0x66, 0x69, 0x6e, 0x64, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_bkfind_bkfind_proto_rawDescOnce sync.Once
	file_bkfind_bkfind_proto_rawDescData = file_bkfind_bkfind_proto_rawDesc
)

func file_bkfind_bkfind_proto_rawDescGZIP() []byte {
	file_bkfind_bkfind_proto_rawDescOnce.Do(func() {
		file_bkfind_bkfind_proto_rawDescData = protoimpl.X.CompressGZIP(file_bkfind_bkfind_proto_rawDescData)
	})
	return file_bkfind_bkfind_proto_rawDescData
}

var file_bkfind_bkfind_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_bkfind_bkfind_proto_goTypes = []interface{}{
	(*BReq)(nil),   // 0: bkfind.BReq
	(*BReply)(nil), // 1: bkfind.BReply
	(*AReq)(nil),   // 2: bkfind.AReq
	(*AReply)(nil), // 3: bkfind.AReply
}
var file_bkfind_bkfind_proto_depIdxs = []int32{
	0, // 0: bkfind.Finder.FindBooks:input_type -> bkfind.BReq
	2, // 1: bkfind.Finder.FindAuthors:input_type -> bkfind.AReq
	1, // 2: bkfind.Finder.FindBooks:output_type -> bkfind.BReply
	3, // 3: bkfind.Finder.FindAuthors:output_type -> bkfind.AReply
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_bkfind_bkfind_proto_init() }
func file_bkfind_bkfind_proto_init() {
	if File_bkfind_bkfind_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_bkfind_bkfind_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bkfind_bkfind_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bkfind_bkfind_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bkfind_bkfind_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bkfind_bkfind_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bkfind_bkfind_proto_goTypes,
		DependencyIndexes: file_bkfind_bkfind_proto_depIdxs,
		MessageInfos:      file_bkfind_bkfind_proto_msgTypes,
	}.Build()
	File_bkfind_bkfind_proto = out.File
	file_bkfind_bkfind_proto_rawDesc = nil
	file_bkfind_bkfind_proto_goTypes = nil
	file_bkfind_bkfind_proto_depIdxs = nil
}
