// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: bkfind/bkfind.proto

package bkfind

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// FinderClient is the client API for Finder service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FinderClient interface {
	FindBooks(ctx context.Context, in *BReq, opts ...grpc.CallOption) (*BReply, error)
	FindAuthor(ctx context.Context, in *AReq, opts ...grpc.CallOption) (*AReply, error)
}

type finderClient struct {
	cc grpc.ClientConnInterface
}

func NewFinderClient(cc grpc.ClientConnInterface) FinderClient {
	return &finderClient{cc}
}

func (c *finderClient) FindBooks(ctx context.Context, in *BReq, opts ...grpc.CallOption) (*BReply, error) {
	out := new(BReply)
	err := c.cc.Invoke(ctx, "/bkfind.Finder/FindBooks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *finderClient) FindAuthor(ctx context.Context, in *AReq, opts ...grpc.CallOption) (*AReply, error) {
	out := new(AReply)
	err := c.cc.Invoke(ctx, "/bkfind.Finder/FindAuthor", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FinderServer is the server API for Finder service.
// All implementations must embed UnimplementedFinderServer
// for forward compatibility
type FinderServer interface {
	FindBooks(context.Context, *BReq) (*BReply, error)
	FindAuthor(context.Context, *AReq) (*AReply, error)
	mustEmbedUnimplementedFinderServer()
}

// UnimplementedFinderServer must be embedded to have forward compatible implementations.
type UnimplementedFinderServer struct {
}

func (UnimplementedFinderServer) FindBooks(context.Context, *BReq) (*BReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindBooks not implemented")
}
func (UnimplementedFinderServer) FindAuthor(context.Context, *AReq) (*AReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindAuthor not implemented")
}
func (UnimplementedFinderServer) mustEmbedUnimplementedFinderServer() {}

// UnsafeFinderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FinderServer will
// result in compilation errors.
type UnsafeFinderServer interface {
	mustEmbedUnimplementedFinderServer()
}

func RegisterFinderServer(s grpc.ServiceRegistrar, srv FinderServer) {
	s.RegisterService(&Finder_ServiceDesc, srv)
}

func _Finder_FindBooks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinderServer).FindBooks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bkfind.Finder/FindBooks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinderServer).FindBooks(ctx, req.(*BReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Finder_FindAuthor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinderServer).FindAuthor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bkfind.Finder/FindAuthor",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinderServer).FindAuthor(ctx, req.(*AReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Finder_ServiceDesc is the grpc.ServiceDesc for Finder service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Finder_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bkfind.Finder",
	HandlerType: (*FinderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindBooks",
			Handler:    _Finder_FindBooks_Handler,
		},
		{
			MethodName: "FindAuthor",
			Handler:    _Finder_FindAuthor_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bkfind/bkfind.proto",
}
